#!/usr/bin/env bash

if ! [ -d "/opt/DoggeHook/data" ]; then
	echo "Creating DoggeHook data directory at /opt/DoggeHook/data"
	mkdir -p "/opt/DoggeHook/data"
	chown -R $USER "/opt/DoggeHook/data"
	chmod -R 777 "/opt/DoggeHook/data"
fi

echo "Installing cathook data to /opt/cathook/data"
rsync -avh --progress "data/" "/opt/cathook/data"
