#!/usr/bin/env bash
printf "\n\n";printf '\e[1;34m%-6s\e' "WARNING: THIS BRANCH IS OUTDATED! Please reinstall cathook by following the install instructions on https://github.com/nullworks/cathook";printf "\n\n"
#Get updated source code
git fetch;git pull origin;git submodule update --init --recursive
#Update cathook
cd build; cmake ..; make -j$(grep -c '^processor' /proc/cpuinfo)
#Update data
sudo make data;  cd ..; cd ..
printf "\n\n";printf '\e[1;34m%-6s\e' "Cathook update complete!";printf "\n\n"
